---
kind: pipeline
name: default

steps:
    - name: unit-tests
      image: signalwire/freeswitch-public-base
      pull: true
      commands:
      - export WORK_DIR=$PWD
      - echo $WORK_DIR
      - export ASAN_OPTIONS=log_path=stdout:disable_coredump=0:unmap_shadow_on_exit=1;
      - ./bootstrap.sh
      - ./configure --enable-address-sanitizer
      - echo '#!/bin/bash\nmake -j`nproc --all` |& tee $WORK_DIR/unit-tests-build-result.txt\nexitstatus=$${PIPESTATUS[0]}\necho $$exitstatus > $WORK_DIR/build-status.txt\n' > build.sh
      - chmod +x build.sh
      - ./build.sh
      - mkdir -p $WORK_DIR/tests/unit
      - cat /proc/sys/kernel/core_pattern
      - ./run-tests-parallel.sh 
      - echo 0 > $WORK_DIR/tests/unit/run-tests-status.txt
      - ./collect-test-logs.sh && exit 0 || echo 'Some tests failed'
      - ls -la ./test
      - echo 1 > $WORK_DIR/tests/unit/run-tests-status.txt
      - ls -la /cores
      - mkdir -p $WORK_DIR/tests/unit/logs
      - (mv artifacts.html $WORK_DIR/tests/unit/logs/ || true)
      - (mv log_run-tests_*.html $WORK_DIR/tests/unit/logs/ || true)
      - (mv backtrace_*.txt $WORK_DIR/tests/unit/logs/ || true)
      - ls -la $WORK_DIR/tests/unit/logs

    - name: notify
      image: signalwire/unit-tests-notify
      pull: true
      environment:
        GITHUB_CI_APP_PEM:
          from_secret: github_ci_app_pem
        SSH_KEY:
          from_secret: ssh_key
        SLACK_WEBHOOK_URL:
          from_secret: slack_webhook_url
      commands:
      - /root/notify.sh
      
trigger:
  branch:
  - master
  event:
  - pull_request
  - push

---
kind: pipeline
name: scan-build

node:
  freeswitch: stack

steps:
    - name: scan-build
      image: signalwire/freeswitch-public-base
      pull: true
      commands:
      - ./bootstrap.sh
      - ./configure
      - mkdir -p scan-build
      - echo '#!/bin/bash\nscan-build-7 -o ./scan-build/ make -j`nproc --all` |& tee ./scan-build-result.txt\nexitstatus=$${PIPESTATUS[0]}\necho $$exitstatus > ./scan-build-status.txt\n' > scan.sh
      - chmod +x scan.sh
      - ./scan.sh
      - exitstatus=`cat ./scan-build-status.txt`
      - echo "*** Exit status is $exitstatus"

    - name: notify
      image: signalwire/scan-build-notify
      pull: true
      environment:
        GITHUB_CI_APP_PEM:
          from_secret: github_ci_app_pem
        SSH_KEY:
          from_secret: ssh_key
        SLACK_WEBHOOK_URL:
          from_secret: slack_webhook_url
      commands:
      - /root/notify.sh

      
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
---
kind: signature
hmac: 36ee86f9800cdb47211993021f96f97d0535f928aaf001eb44dd18ca3a8ddf04

...
